import Link from "next/link";
import type { Metadata } from "next";
import { ArrowLeft } from "lucide-react";
import { Logo } from "@/components/branding/logo";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How CreatixReach collects, uses, shares and protects personal information across creatixreach.io and CreatixApp.",
};

const EFFECTIVE_DATE = "July 28, 2026";

type Section = {
  heading: string;
  body?: string[];
  bulletsHeading?: string;
  bullets?: string[];
  bulletsAfter?: string[];
};

const SECTIONS: Section[] = [
  {
    heading: "1. Who we are",
    body: [
      "CreatixReach is a registered company in the United States. In this Privacy Policy, CreatixReach, we, us and our mean that company.",
      "This policy explains how we handle personal information across everything we operate, including this website at creatixreach.io, CreatixApp (our customer portal at app.creatixreach.io), the hosted dialer environments we provision for customers, and the email, billing and support systems behind them. We refer to all of this together as the Service.",
      "If you have a question about this policy, or you want to exercise a privacy right described below, email us at info@creatixreach.io.",
    ],
  },
  {
    heading: "2. Two different roles we play",
    body: [
      "CreatixReach handles personal information in two distinct capacities, and your rights differ depending on which one applies.",
    ],
    bullets: [
      "As a controller. When you visit this website, contact us, sign up for an account, complete verification, pay us, or open a support ticket, we decide why and how your information is used. This policy governs that information.",
      "As a processor. When a customer uploads contact lists, dials numbers, records calls or runs campaigns through CreatixApp and its dialer, that data belongs to the customer. We process it only to run the Service on their behalf and under their instructions. If you were contacted by a business that uses CreatixReach and you want your data corrected or removed, contact that business directly. If you reach out to us, we will pass your request to the relevant customer.",
    ],
  },
  {
    heading: "3. Information we collect",
    bulletsHeading: "Information you give us",
    bullets: [
      "Contact and account details: name, business name, email address, phone number, country, and the credentials used to sign in.",
      "Verification information: the identity or business documentation we ask for before an account is activated. We collect this to prevent fraud and abuse of telecommunications infrastructure, and we keep only what we need for that purpose.",
      "Billing information: plan selected, seat count, calling credit balance, transaction records, and the wallet or transaction identifiers associated with cryptocurrency payments. We do not receive or store card numbers, bank details or private keys.",
      "Communications: messages you send through our contact form, support tickets, and email correspondence with our team.",
    ],
    bulletsAfter: [
      "Information we collect automatically. When you use this website or CreatixApp we collect log and device data such as IP address, browser type, operating system, referring page, pages viewed, timestamps and general location inferred from IP. We use privacy-conscious analytics to understand traffic volume and referral sources in aggregate.",
      "Service data generated by use of the platform. Running a dialer produces operational records: call detail records (numbers dialed, timestamps, duration, disposition and outcome), agent and seat activity, provisioning and system logs, and billing events derived from call minutes. Some of this data is personal information about the people your agents call.",
      "Customer content. Customers upload lead and contact lists, campaign configuration, scripts, and in some configurations call recordings. We do not select, review or use this content for our own purposes.",
    ],
  },
  {
    heading: "4. How we use information",
    bullets: [
      "To create, verify, provision and maintain accounts, dialer environments, phone numbers and agent seats.",
      "To calculate charges: subscription fees, per-minute call billing, number rental, and prepaid calling credit balances, including suspending service when a balance reaches zero.",
      "To provide support, respond to tickets and contact form submissions, and send service notices such as verification, provisioning, billing, low balance and suspension emails.",
      "To secure the Service: detect and prevent fraud, toll fraud, credential abuse, unlawful calling traffic and other misuse, and to respond to carrier or regulator complaints.",
      "To improve the Service, measure which pages and campaigns bring in interest, and plan capacity.",
      "To comply with legal obligations, enforce our Terms of Service, and establish or defend legal claims.",
      "To send occasional marketing email about CreatixReach where permitted by law. You can opt out at any time. Service and billing emails continue because they are necessary to operate your account.",
    ],
  },
  {
    heading: "5. Legal bases (EEA, UK and similar jurisdictions)",
    body: [
      "Where data protection law requires a legal basis, we rely on: performance of a contract (providing and billing the Service); legitimate interests (security, fraud prevention, service improvement and business communications), balanced against your rights; legal obligation (tax, accounting, lawful requests and telecommunications compliance); and consent, where we ask for it, which you can withdraw at any time.",
    ],
  },
  {
    heading: "6. Cookies and similar technologies",
    body: [
      "We use cookies and equivalent browser storage that are strictly necessary to keep you signed in, maintain session security and remember basic preferences, plus a limited set of analytics cookies that measure page views and referral sources. We do not use advertising cookies to build cross-site profiles of you. Where we run advertising measurement, it is limited to understanding whether a campaign produced visits or signups.",
      "You can block or delete cookies in your browser. Strictly necessary cookies cannot be disabled without breaking sign-in and the portal.",
    ],
  },
  {
    heading: "7. How we share information",
    body: [
      "We do not sell personal information, and we do not share it with third parties for their own marketing.",
    ],
    bulletsHeading: "We share information only with:",
    bullets: [
      "Service providers who run parts of the platform under contract: cloud hosting and virtual machine infrastructure, telecommunications carriers and number providers, authentication, database hosting, transactional email delivery, DNS and network security, payment processing, analytics, and error monitoring. They may process personal information only to perform services for us.",
      "Professional advisors such as accountants and lawyers, where necessary.",
      "Authorities, carriers or complainants, where we are legally required to respond or where it is necessary to investigate suspected illegal calling activity or protect the rights and safety of others.",
      "A successor entity, in connection with a merger, acquisition, financing or sale of assets, subject to this policy continuing to apply.",
    ],
  },
  {
    heading: "8. International transfers",
    body: [
      "CreatixReach is a United States company, and our infrastructure and service providers are located in the United States, the European Union and other regions. Using the Service therefore involves transferring information across borders, including to countries whose data protection laws differ from those where you live. Where required, we rely on recognized transfer mechanisms such as the European Commission standard contractual clauses and equivalent UK provisions, together with contractual and technical safeguards.",
    ],
  },
  {
    heading: "9. How long we keep information",
    body: [
      "We keep account, billing and verification records for as long as the account is active, and afterwards for the period needed to meet tax, accounting, anti-fraud and legal obligations. Operational records such as call detail records and system logs are retained for a limited period for billing accuracy, dispute resolution and security investigation, then deleted or aggregated. Customer content stays under the control of the customer and is deleted when the customer deletes it or, after account closure, when the environment is decommissioned. Backups are cycled out on their own schedule.",
    ],
  },
  {
    heading: "10. Security",
    body: [
      "We use encryption in transit, isolated per-customer dialer environments, restricted administrative access, network filtering and automated intrusion blocking, signed webhooks between systems, and audit logging of sensitive administrative actions. No system is perfectly secure, and we cannot guarantee absolute security. You are responsible for keeping your credentials confidential, using strong unique passwords, and telling us promptly at info@creatixreach.io if you suspect unauthorized access.",
    ],
  },
  {
    heading: "11. Your privacy rights",
    body: [
      "Depending on where you live, you may have the right to access the personal information we hold about you, to correct it, to delete it, to restrict or object to certain processing, to receive a portable copy, and to withdraw consent. To exercise a right, email info@creatixreach.io. We will verify your identity before acting and respond within the period required by applicable law. You may also complain to your local data protection authority.",
      "If your information reached us because a CreatixReach customer loaded it into their own account, we act as a processor and will refer your request to that customer.",
    ],
  },
  {
    heading: "12. United States state privacy rights",
    body: [
      "If you are a resident of California or another US state with a comprehensive privacy law, you may have rights to know what personal information we collect and why, to access and delete it, to correct inaccuracies, and to be free from discrimination for exercising those rights.",
      "We do not sell personal information and we do not share it for cross-context behavioral advertising as those terms are defined under the California Consumer Privacy Act as amended. We do not knowingly process sensitive personal information for purposes that require an opt-out right. To submit a request, email info@creatixreach.io. An authorized agent may submit on your behalf with proof of authorization.",
    ],
  },
  {
    heading: "13. Obligations of customers who call consumers",
    body: [
      "Customers who use CreatixReach to contact consumers are independently responsible for the lawfulness of those contacts. That includes obtaining any consent required before calling or recording, honoring do-not-call requests and applicable do-not-call registries, providing accurate caller identification, respecting calling hours, and giving the notices required by the privacy and telemarketing laws that apply to them and to the people they call. Our Terms of Service set out these obligations in more detail, and breaching them is grounds for immediate suspension.",
    ],
  },
  {
    heading: "14. Children",
    body: [
      "The Service is a business tool and is not directed to children. We do not knowingly collect personal information from anyone under 18. If you believe a child has provided us with personal information, email info@creatixreach.io and we will delete it.",
    ],
  },
  {
    heading: "15. Third-party links",
    body: [
      "This website and the portal may link to sites and services we do not control, including payment processors and documentation hosted elsewhere. Their privacy practices are their own, and we encourage you to read their policies.",
    ],
  },
  {
    heading: "16. Changes to this policy",
    body: [
      "We may update this policy as the Service evolves or the law changes. The effective date at the top of this page always reflects the current version. If a change is material, we will give notice by email or through the portal before it takes effect. Continuing to use the Service after a change takes effect means you accept the updated policy.",
    ],
  },
  {
    heading: "17. Contact us",
    body: [
      "Questions, requests or complaints about privacy: info@creatixreach.io. We read every message and respond as quickly as we can.",
    ],
  },
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-brand-navy text-brand-text-dark">
      <header className="sticky top-0 z-40 w-full border-b border-white/10 bg-brand-navy/80 backdrop-blur">
        <div className="container flex h-16 items-center justify-between">
          <Logo size="sm" />
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-sm text-brand-muted-dark transition-colors hover:text-brand-text-dark"
          >
            <ArrowLeft className="h-4 w-4" />
            Back home
          </Link>
        </div>
      </header>
      <main className="container py-16 md:py-24">
        <div className="mx-auto max-w-2xl">
          <h1 className="text-4xl font-bold tracking-tight md:text-5xl">
            Privacy Policy
          </h1>
          <p className="mt-4 text-sm uppercase tracking-[0.25em] text-brand-muted-dark">
            Effective {EFFECTIVE_DATE}
          </p>
          <p className="mt-8 text-base leading-relaxed text-brand-muted-dark">
            CreatixReach is a registered company in the United States providing
            hosted call center and outbound calling software, including
            CreatixApp, our customer portal at app.creatixreach.io. This policy
            explains what personal information we collect, why we collect it, who
            we share it with, and the choices you have.
          </p>

          <div className="mt-14 space-y-12">
            {SECTIONS.map((section) => (
              <section key={section.heading}>
                <h2 className="text-xl font-semibold text-brand-text-dark">
                  {section.heading}
                </h2>

                {section.body ? (
                  <div className="mt-4 space-y-4">
                    {section.body.map((paragraph, index) => (
                      <p
                        key={index}
                        className="text-base leading-relaxed text-brand-muted-dark"
                      >
                        {paragraph}
                      </p>
                    ))}
                  </div>
                ) : null}

                {section.bulletsHeading ? (
                  <p className="mt-4 text-base font-medium leading-relaxed text-brand-text-dark">
                    {section.bulletsHeading}
                  </p>
                ) : null}

                {section.bullets ? (
                  <ul className="mt-4 space-y-3">
                    {section.bullets.map((item, index) => (
                      <li
                        key={index}
                        className="flex gap-3 text-base leading-relaxed text-brand-muted-dark"
                      >
                        <span
                          aria-hidden="true"
                          className="mt-3 h-1.5 w-1.5 flex-none rounded-full bg-brand-indigo"
                        />
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                ) : null}

                {section.bulletsAfter ? (
                  <div className="mt-4 space-y-4">
                    {section.bulletsAfter.map((paragraph, index) => (
                      <p
                        key={index}
                        className="text-base leading-relaxed text-brand-muted-dark"
                      >
                        {paragraph}
                      </p>
                    ))}
                  </div>
                ) : null}
              </section>
            ))}
          </div>

          <div className="mt-16 border-t border-white/10 pt-8 text-sm text-brand-muted-dark">
            <p>
              Questions about this policy? Email{" "}
              <a
                href="mailto:info@creatixreach.io"
                className="text-brand-indigo hover:underline"
              >
                info@creatixreach.io
              </a>
              .
            </p>
            <p className="mt-3">
              See also our{" "}
              <Link href="/terms" className="text-brand-indigo hover:underline">
                Terms of Service
              </Link>
              .
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
